#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""

    Nom : Warriors Smash

    Description : un jeu

    Modules : Tkinter, time


"""


from tkinter import *
from time import *










#-------------------------- Programme principal----------------------
fen1 = Tk()
tex1 = Label(fen1, text='Bonjour tout le monde !', fg='red')
tex1.pack()
bou1 = Button(fen1, text='Quitter', command = fen1.destroy)
bou1.pack()
fen1.mainloop()
        
